// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sztmdlickitthspdeepx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6dG1kbGlja2l0dGhzcGRlZXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjA0NTAsImV4cCI6MjA2MDQ5NjQ1MH0.a7u6VO6ID1g4JZ6celFdGqVC8a115qxZZMkr4UPDRaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);